Abbreviation component
DarkFlorist/TheInterceptor pull request #949
Opened 2024-04-08 12:21 UTC by jubalm

- [x] find instances on where this component can be used
- [x] create or replace test

2024-04-10 09:34 UTC, KillariDev commented
is there still use for `bigintToDecimalString` or should it also be removed? The tests should also apply to this and not the old funtction

2024-04-18 05:12 UTC, jubalm commented
I've updated the test and just realized Docker build is using node 18 which doesn't support the new Intl.NumberFormat options (roundingMode). We can either update the test, update Node to 20 (LTS) or just update the code. would like to know your opinions before i go at it again @KillariDev @MicahZoltu

2024-04-18 09:13 UTC, KillariDev requested changes
when performing a swap, this is what I see:
<img width="519" alt="image" src="https://github.com/DarkFlorist/TheInterceptor/assets/13102010/b5a692fc-0eb3-43c7-9a0b-723687bd0ca6">

2024-04-18 09:13 UTC, KillariDev commented on app/ts/components/subcomponents/coins.tsx
> +				<AbbreviatedValue amount={param.amount} decimals={param.tokenEntry.decimals} />
```suggestion
				<AbbreviatedValue amount = { param.amount } decimals = { param.tokenEntry.decimals } />
```

2024-04-18 09:13 UTC, KillariDev commented on app/ts/utils/bigint.ts
> +	// roundingMode is not supported until https://github.com/microsoft/TypeScript/pull/56902 (merged)
```suggestion
```

2024-04-18 09:13 UTC, KillariDev commented on app/ts/utils/bigint.ts
> +	const formatter = new Intl.NumberFormat('en-US', formatOptions )
```suggestion
	const formatter = new Intl.NumberFormat('en-US', formatOptions)
```

2024-04-18 09:13 UTC, KillariDev commented on test/tests/utils.bigint.ts
> +		should('display 00000001 ETH', () => assert.equal(bigintToRoundedPrettyDecimalString(10n ** 10n, 18n, 4), '0.00000001'))
```suggestion
		should('display 0.00000001 ETH', () => assert.equal(bigintToRoundedPrettyDecimalString(10n ** 10n, 18n, 4), '0.00000001'))
```

2024-04-22 14:53 UTC, jubalm commented
> when performing a swap, this is what I see: <img alt="image" width="519" src="https://private-user-images.githubusercontent.com/13102010/323540707-b5a692fc-0eb3-43c7-9a0b-723687bd0ca6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTc3NTAsIm5iZiI6MTcxMzc5NzQ1MCwicGF0aCI6Ii8xMzEwMjAxMC8zMjM1NDA3MDctYjVhNjkyZmMtMGViMy00M2M3LTlhMGItNzIzNjg3YmQwY2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE0NTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0OTNiMTE5Mzc5YzNhNTFmOWVlZjFjZmJjMjM1ZDE0YmQ2YTYwNTFmOWViZjk5Mjc1NzEwM2I4MzMxOTY5OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nUZvF9BccUe136X0AL22cUczsSPahjRlE36rZEz7nYY">

just noticed there was a missing commit, patched on [76ba86f](https://github.com/DarkFlorist/TheInterceptor/pull/949/commits/76ba86f2a04b75e228bd06ecc8c66dfd150314d0) as well as the comments

2024-04-23 09:17 UTC, KillariDev commented on app/ts/components/subcomponents/AbbreviatedValue.tsx
> +			const significantDigits = `${Number(value)}`
```suggestion
			const significantDigits = `${ Number(value) }`
```

2024-04-26 09:09 UTC, jubalm commented
Added additional tests that account for prefixed values 10000 and beyond (and negative equivalent)

2024-04-29 07:20 UTC, merged